---
- name: Configure and deploy sir-bot-a-lot
  hosts: sirbot
  roles:
    - role: common
      tags: configuration
    - role: ntp
      tags: configuration
    - role: fail2ban
      tags: configuration
    - role: sysstat
      tags: configuration
    - role: pyapp
      pyapp_source_dir: '{{source_root}}/sir-bot-a-lot'
      pyapp_dest_archive_dir: '/var/src'
      pyapp_local_venv: '{{ venv_root | expanduser}}/sirbot'
      python_version: python3.5
    - role: nginx
      tags: configuration
    - role: sirbot
      template_root: sirbot
      nginx_app_name: sirbot
  tasks:
    - include: tasks/nginx.yml
      template_root: sirbot
      nginx_app_name: sirbot
