---
- name: Create virtualenv
  become: true
  become_user: "{{ username }}"
  pip:
    name: pip
    version: 9.0.1
    virtualenv: "/home/{{ username }}/.pyvenv"
    virtualenv_command: "/usr/local/pythonz/pythons/CPython-{{ python_version }}/bin/virtualenv"

- name: Clone project
  become: true
  become_user: "{{ username }}"
  git:
    accept_hostkey: yes
    clone: yes
    repo: "{{ repo }}"
    version: "{{ version }}"
    dest: "/home/{{ username }}/{{ service_name }}"
    force: yes
    remote: origin
  register: clone
  notify:
    - Service post install
    - Restart service

- name: Install dependencies
  become: true
  become_user: "{{ username }}"
  pip:
    requirements: "/home/{{ username }}/{{ service_name }}/requirements.txt"
    executable: "/home/{{ username }}/.pyvenv/bin/pip"

- name: Install self
  become: true
  become_user: "{{ username }}"
  pip:
    name: "file:///home/{{ username }}/{{ service_name }}"
    executable: "/home/{{ username }}/.pyvenv/bin/pip"
    state: forcereinstall
  when: 'clone|changed and install_self|bool'
