---

- name: Reload systemd dameon
  systemd:
    name: sirbot.service
    daemon_reload: yes
  notify:
    - Restart sirbot

- name: Restart sirbot
  service:
    name: sirbot.service
    state: restarted

- name: Restart nginx
  service:
    name: nginx.service
    state: restarted
