- name: Create .ssh directory
  file:
    path: /root/.ssh
    state: directory

- name: Set authorized keys
  template:
    src: roles/setup-server/templates/ssh/{{ inventory_hostname }}/authorized_keys.j2
    dest: /root/.ssh/authorized_keys.j2
    owner: root
    mode: 0600

- name: Ssh configuration
  template:
    src: etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
  notify:
    - Restart ssh