---

- name: Create build environment
  become: true
  become_user: sirbot
  pip:
    name: make-deb, pathlib, flake8, pytest-runner
    virtualenv: /home/sirbot/.venv
    virtualenv_python: python3.5
  when:
    - git.changed == True or force_build is defined
    - local_deb is undefined

- name: Configure debian package
  become: true
  shell: |
    source /home/sirbot/.venv/bin/activate
    /home/sirbot/.venv/bin/make-deb
  args:
    chdir: /home/sirbot/build
    executable: /bin/bash
  when:
    - git.changed == True or force_build is defined
    - local_deb is undefined

- name: Register version number
  become: true
  shell: |
    source /home/sirbot/.venv/bin/activate
    python setup.py --version
  args:
    chdir: /home/sirbot/build
    executable: /bin/bash
  register: sirbot_version
  when:
    - git.changed == True or force_build is defined
    - local_deb is undefined

- name: Build debian package
  become: true
  shell: |
    dpkg-buildpackage -us -uc
  environment:
    VIRTUALENV_PYTHON: /usr/bin/python3.5
  args:
    chdir: /home/sirbot/build
  when:
    - git.changed == True or force_build is defined
    - local_deb is undefined

- name: Install package
  become: true
  shell: "dpkg -i sirbot_{{ sirbot_version.stdout }}_amd64.deb"
  args:
    chdir: /home/sirbot
  notify:
    - Restart sirbot
  when:
    - git.changed == True or force_build is defined
    - local_deb is undefined

- name: Copy example.py
  copy:
    remote_src: True
    src: /home/sirbot/build/example.py
    dest: /home/sirbot/example.py
  when:
    - git.changed == True or force_build is defined
    - local_deb is undefined
  notify:
    - Restart sirbot

- name: Delete build/debian directory
  file:
    path: /home/sirbot/build/debian
    state: absent
  when:
    - git.changed == True or force_build is defined
    - local_deb is undefined