---

- name: Copy package
  become: true
  copy:
    src: "{{ local_deb }}"
    dest: /home/sirbot/sirbot.deb
  when:
    - local_deb is defined

- name: Install local package
  become: true
  shell: dpkg -i sirbot.deb
  args:
    chdir: /home/sirbot
  notify:
    - Restart sirbot
  when:
    - local_deb is defined

- name: Copy run.py
  copy:
    src: "{{ local_run }}"
    dest: /home/sirbot/run.py
  when:
    - local_run is defined