---

- name: Install core requirements
  become: true
  become_user: sirbot
  pip:
    requirements: /home/sirbot/sir-bot-a-lot/requirements.txt
    executable: /home/sirbot/.pyvenv/bin/pip
  notify:
    - Restart sirbot

- name: Install core
  become: true
  become_user: sirbot
  pip:
    name: /home/sirbot/sir-bot-a-lot/
    executable: /home/sirbot/.pyvenv/bin/pip
    state: forcereinstall
  when: sirbot_clone_core.changed
  notify:
    - Restart sirbot

- name: Install plugin requirements
  become: true
  become_user: sirbot
  pip:
    requirements: /home/sirbot/sirbot-plugin/requirements.txt
    executable: /home/sirbot/.pyvenv/bin/pip
  notify:
    - Restart sirbot

- name: Install plugin
  become: true
  become_user: sirbot
  pip:
    name: /home/sirbot/sirbot-plugin/
    executable: /home/sirbot/.pyvenv/bin/pip
    state: forcereinstall
  when: sirbot_clone_plugin.changed
  notify:
    - Restart sirbot

- name: Install plugin-slack requirements
  become: true
  become_user: sirbot
  pip:
    requirements: /home/sirbot/sirbot-plugin-slack/requirements.txt
    executable: /home/sirbot/.pyvenv/bin/pip
  notify:
    - Restart sirbot

- name: Install plugin-slack
  become: true
  become_user: sirbot
  pip:
    name: /home/sirbot/sirbot-plugin-slack/
    executable: /home/sirbot/.pyvenv/bin/pip
    state: forcereinstall
  when: sirbot_clone_plugin_slack.changed
  notify:
    - Restart sirbot

- name: Install plugin-pythondev requirements
  become: true
  become_user: sirbot
  pip:
    requirements: /home/sirbot/sirbot-plugin-pythondev/requirements.txt
    executable: /home/sirbot/.pyvenv/bin/pip
  notify:
    - Restart sirbot

- name: Install plugin-pythondev
  become: true
  become_user: sirbot
  pip:
    name: /home/sirbot/sirbot-plugin-pythondev/
    executable: /home/sirbot/.pyvenv/bin/pip
    state: forcereinstall
  when: sirbot_clone_plugin_pythondev.changed
  notify:
    - Restart sirbot
