---

- name: Set sirbot in systemd
  become: true
  template:
    src: etc/systemd/system/sirbot.service.j2
    dest: /etc/systemd/system/sirbot.service
  notify:
    - Restart sirbot
    - Reload systemd dameon

- name: Start sirbot on boot
  become: true
  systemd:
    name: sirbot.service
    enabled: yes