---

- name: Create sirbot user
  become: true
  user:
    name: sirbot
    shell: /bin/bash

- name: Create /home/sirbot
  become: true
  file:
    path: /home/sirbot
    state: directory
    mode: 0755